import { colors } from '../theme/colors';

export const appLayoutStyles = {
  appTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 62,
    paddingHorizontal: 8,
  },
  appTopBarGradient: {
    borderRadius: 22,
    elevation: 3,
    marginBottom: 4,
    overflow: 'hidden',
    shadowColor: colors.purple,
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  compactPageHeader: {
    alignItems: 'center',
    borderRadius: 20,
    gap: 3,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  compactPageTitle: {
    color: colors.ink,
    fontFamily: 'Nunito_800ExtraBold',
    letterSpacing: 0,
    textAlign: 'center',
  },
  compactPageSubtitle: { color: colors.muted, textAlign: 'center' },
  logoRow: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 2 },
  topLogoIcon: { height: 42, width: 42 },
  topLogoWord: { height: 46, width: 118 },
  topBrandName: { color: colors.purple, fontWeight: '900' },
  topActions: { alignItems: 'center', flexDirection: 'row', gap: 2 },
  topAvatar: {
    backgroundColor: colors.lavender,
    borderColor: colors.yellow,
    borderWidth: 2,
  },
  brandHero: {
    backgroundColor: colors.lavender,
    borderRadius: 22,
    overflow: 'hidden',
  },
  welcomeCard: {
    backgroundColor: '#F0FBF8',
    borderColor: '#DDF8F0',
    borderRadius: 20,
    borderWidth: 1,
  },
  gradientCard: {
    backgroundColor: colors.purple,
    borderBottomColor: colors.teal,
    borderBottomWidth: 5,
    borderRadius: 20,
    borderRightColor: colors.yellow,
    borderRightWidth: 5,
  },
  gradientCardTitle: { color: colors.white, fontWeight: '900' },
  gradientCardSubtitle: { color: colors.white, opacity: 0.92 },
  brandHeroContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    minHeight: 128,
  },
  brandHeroInner: { padding: 16 },
  brandHeroTitle: { color: colors.ink, fontWeight: '900', lineHeight: 32 },
  brandHeroSubtitle: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
  heroLogoMark: { height: 118, opacity: 0.95, width: 118 },
  bottomMenu: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderTopColor: colors.line,
    borderTopWidth: 1,
    bottom: 0,
    elevation: 12,
    flexDirection: 'row',
    justifyContent: 'space-around',
    left: 0,
    paddingBottom: 10,
    paddingTop: 8,
    position: 'absolute',
    right: 0,
  },
  bottomMenuItem: { alignItems: 'center', flex: 1, minHeight: 64 },
  bottomIconWrap: {
    alignItems: 'center',
    borderRadius: 16,
    height: 40,
    justifyContent: 'center',
    width: 46,
  },
  bottomIcon: { margin: 0 },
  bottomPrimaryButton: {
    backgroundColor: colors.purple,
    borderRadius: 28,
    height: 58,
    marginTop: -26,
    width: 58,
  },
  bottomActive: { backgroundColor: '#F2ECFF' },
  bottomLabel: { color: colors.muted, fontSize: 11, marginTop: 2 },
  bottomLabelActive: { color: colors.purple, fontWeight: '800' },
  sideOverlay: { flex: 1, flexDirection: 'row' },
  sideDim: {
    backgroundColor: 'rgba(0,0,0,0.38)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  sidePanel: {
    backgroundColor: colors.white,
    borderBottomRightRadius: 8,
    borderTopRightRadius: 8,
    elevation: 16,
    overflow: 'hidden',
    width: '82%',
  },
  sideHeader: { minHeight: 190, padding: 22, paddingTop: 34 },
  sideClose: { alignSelf: 'flex-end', margin: 0 },
  sideAvatar: { backgroundColor: colors.white, marginBottom: 12 },
  sideName: { color: colors.white, fontWeight: '900' },
  sideRole: { color: colors.white, opacity: 0.9 },
  sideItems: { padding: 14 },
  sideItem: {
    alignItems: 'center',
    borderRadius: 16,
    flexDirection: 'row',
    minHeight: 54,
  },
  sideItemText: { color: colors.ink, flex: 1, fontSize: 16, fontWeight: '700' },
  aboutCard: { backgroundColor: colors.white, borderRadius: 20 },
  aboutTitle: { color: colors.purple },
  aboutLogo: { alignSelf: 'center', height: 180, width: '100%' },
};
