import { Platform } from 'react-native';

import { colors } from '../theme/colors';

const isWeb = Platform.OS === 'web';

export const dataDisplayStyles = {
  avatarTeal: { backgroundColor: colors.teal },
  avatarPurple: { backgroundColor: colors.purple },
  avatarLavender: { backgroundColor: colors.lavender },
  avatarInactive: { backgroundColor: colors.inactive },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    ...(isWeb && {
      gap: 12,
    }),
  },
  statCard: {
    borderRadius: 18,
    flexBasis: '31%',
    flexGrow: 1,
    minWidth: 104,
    ...(isWeb && {
      borderRadius: 12,
      flexBasis: 0,
      maxWidth: 260,
      minWidth: 180,
    }),
  },
  statContent: { alignItems: 'center', gap: 6 },
  statValue: { color: colors.ink, fontWeight: '900' },
  quickGrid: { gap: 10 },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    ...(isWeb && {
      gap: 12,
    }),
  },
  actionTile: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    elevation: 1,
    flexBasis: '30%',
    flexGrow: 1,
    gap: 6,
    minHeight: 106,
    padding: 10,
    shadowColor: '#0F172A',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    ...(isWeb && {
      borderRadius: 12,
      flexBasis: 0,
      maxWidth: 210,
      minHeight: 96,
      minWidth: 150,
      padding: 14,
    }),
  },
  actionIconCircle: { backgroundColor: '#F2ECFF', margin: 0 },
  actionTileText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  sectionTitle: { color: colors.ink, fontWeight: '800' },
  search: {
    backgroundColor: colors.white,
    borderColor: colors.inputBorder,
    borderRadius: 22,
    borderWidth: 1,
    elevation: 0,
    ...(isWeb && {
      borderRadius: 12,
    }),
  },
  itemRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 12 },
  itemTitle: { color: colors.ink, fontWeight: '800' },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  statusChip: { alignSelf: 'flex-start', marginTop: 8 },
  divider: { marginVertical: 12 },
  rowEnd: { alignItems: 'center', flexDirection: 'row', justifyContent: 'flex-end' },
  fab: { backgroundColor: colors.yellow, bottom: 104, position: 'absolute', right: 22 },
  empty: { alignItems: 'center', gap: 12, paddingVertical: 22 },
  emptyInline: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    gap: 10,
    paddingVertical: 18,
    ...(isWeb && {
      borderRadius: 12,
    }),
  },
  profileHeader: { alignItems: 'center', flexDirection: 'row', gap: 14 },
  profilePhoto: { borderRadius: 38, height: 76, width: 76 },
  profilePhotoPicker: {
    alignItems: 'center',
    backgroundColor: colors.tealSoft,
    borderColor: '#C8EEE5',
    borderRadius: 20,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  profilePhotoLarge: {
    borderColor: colors.white,
    borderRadius: 56,
    borderWidth: 4,
    height: 112,
    width: 112,
  },
  profilePhotoActions: { alignItems: 'center', gap: 4, width: '100%' },
  fileActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
    marginTop: 8,
  },
  infoLabel: { color: colors.muted, fontSize: 12, fontWeight: '700', textTransform: 'uppercase' },
  infoValue: { color: colors.ink, fontSize: 15, lineHeight: 21 },
  infoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  infoTile: {
    backgroundColor: colors.white,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    gap: 4,
    padding: 10,
    ...(isWeb && {
      borderRadius: 12,
      flexBasis: '31%',
    }),
  },
  infoTileFull: { flexBasis: '100%' },
};
