import { colors } from '../theme/colors';

export const feedbackStyles = {
  appDialog: {
    alignSelf: 'center',
    backgroundColor: colors.white,
    borderRadius: 18,
    marginHorizontal: 20,
    maxWidth: 520,
    width: '90%',
  },
  appDialogTitle: { color: colors.ink, fontWeight: '800', marginBottom: 4 },
  appDialogContent: { gap: 14 },
  appDialogText: { color: colors.ink, fontSize: 16, lineHeight: 23 },
  appDialogActions: {
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'flex-end',
    paddingHorizontal: 20,
    paddingBottom: 18,
  },
  temporaryPassword: {
    backgroundColor: colors.tealSoft,
    borderRadius: 12,
    color: colors.tealDark,
    fontWeight: '900',
    letterSpacing: 2,
    padding: 16,
    textAlign: 'center',
  },
  feedbackSnackbarWrapper: {
    left: 12,
    right: 12,
  },
  feedbackSnackbar: {
    alignSelf: 'center',
    borderRadius: 8,
    maxWidth: 560,
    minHeight: 52,
    width: '100%',
  },
  feedbackSnackbarSuccess: { backgroundColor: '#ECFDF3' },
  feedbackSnackbarError: { backgroundColor: '#FEF3F2' },
  feedbackSnackbarWarning: { backgroundColor: colors.yellowSoft },
  feedbackSnackbarInfo: { backgroundColor: colors.lavenderSoft },
  feedbackSnackbarContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 28,
  },
  feedbackSnackbarText: {
    color: colors.ink,
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  inlineFeedback: {
    alignItems: 'flex-start',
    borderLeftWidth: 4,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inlineFeedbackSuccess: {
    backgroundColor: '#ECFDF3',
    borderLeftColor: colors.tealDark,
  },
  inlineFeedbackError: {
    backgroundColor: '#FEF3F2',
    borderLeftColor: colors.danger,
  },
  inlineFeedbackWarning: {
    backgroundColor: colors.yellowSoft,
    borderLeftColor: '#946200',
  },
  inlineFeedbackInfo: {
    backgroundColor: colors.lavenderSoft,
    borderLeftColor: colors.purple,
  },
  inlineFeedbackText: {
    color: colors.ink,
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
};
