import { colors } from '../theme/colors';

export const sessionStyles = {
  sessionHeader: { borderRadius: 0 },
  sessionPage: { backgroundColor: colors.bg },
  sessionPageScroll: { paddingBottom: 42 },
  sessionHero: {
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    marginBottom: 22,
    padding: 16,
    paddingBottom: 24,
  },
  sessionSummaryCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    elevation: 4,
    shadowColor: colors.purple,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
  },
  sessionSummaryContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 88,
  },
  sessionMeta: { color: colors.muted, fontSize: 14, lineHeight: 24 },
  sessionMetaStrong: { color: colors.ink, fontFamily: 'Nunito_800ExtraBold' },
  sessionElapsedBox: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  sessionClockIcon: { backgroundColor: colors.lavenderSoft },
  sessionElapsed: { color: colors.purple, fontFamily: 'Nunito_800ExtraBold' },
  sessionSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  sessionHorizontalPadding: { paddingHorizontal: 16 },
  sessionActionGroup: { gap: 10, paddingHorizontal: 16 },
  sessionStudentsRow: { gap: 10, paddingHorizontal: 16, paddingVertical: 12 },
  sessionStudentCard: {
    backgroundColor: colors.white,
    borderBottomWidth: 4,
    borderRadius: 18,
    elevation: 2,
    minWidth: 190,
  },
  sessionStudentContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 72,
    paddingHorizontal: 10,
  },
  sessionRecordCount: { color: colors.tealDark, fontSize: 12, fontWeight: '800' },
  sessionShortcutGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    padding: 16,
    paddingTop: 12,
  },
  sessionShortcutCard: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    elevation: 1,
    flexBasis: '21%',
    flexGrow: 1,
    gap: 7,
    justifyContent: 'center',
    minHeight: 105,
    minWidth: 72,
    padding: 8,
  },
  sessionShortcutCardSelected: {
    backgroundColor: colors.white,
    elevation: 2,
  },
  sessionShortcutCardPressed: { opacity: 0.82 },
  sessionShortcutIcon: {
    alignItems: 'center',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  sessionShortcutText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 15,
    textAlign: 'center',
  },
  newObservationButton: {
    alignItems: 'center',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginHorizontal: 16,
    minHeight: 60,
    paddingHorizontal: 18,
  },
  newObservationText: { color: colors.white, fontFamily: 'Nunito_800ExtraBold' },
  sessionStopButton: { borderRadius: 18, marginHorizontal: 16, marginTop: 12 },
  sessionStopDanger: { borderColor: colors.danger },
  sessionStopButtonContent: { minHeight: 64 },
  sessionContent: { flex: 1, padding: 16 },
  sessionScroll: { gap: 12, paddingBottom: 40 },
  timelineHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  timelineTime: { color: colors.tealDark, fontWeight: '900' },
  sheetBackdrop: {
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  bottomSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '88%',
  },
  bottomSheetContent: { gap: 12, padding: 16, paddingBottom: 32 },
  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  activeSessionCard: { borderColor: colors.teal, borderWidth: 1 },
  activeChip: { backgroundColor: '#DDF8F0' },
  dialogEmphasis: { fontWeight: '800' },
  observationSaveContent: { minHeight: 52 },
  observationActions: { flexDirection: 'row', gap: 8 },
  observationActionButton: { flex: 1 },
  observationDeleteButton: { borderColor: colors.danger, flex: 1 },
};
