package elovia.eloviaapi.dto;

import java.util.List;

public record AnamneseRequest(
		String professorSalaRecursos,
		String profissionalApoio,
		String funcaoProfissionalApoio,
		String motivoMatriculaSrm,
		String quemEAluno,
		String ondeMora,
		List<String> comQuemMora,
		String desenvolvimento,
		String gestacao,
		String complicacoesParto,
		Boolean possuiIrmaos,
		Integer quantidadeIrmaos,
		List<String> comunicacao,
		Boolean usaMedicacao,
		List<AnamneseMedicamentoRequest> medicamentos,
		List<AnamneseTerapiaRequest> terapias,
		String alergias,
		String restricoesAlimentares,
		String crisesRecorrentes,
		String informacoesMedicas,
		String potencialidades,
		String interesses,
		String maiorFacilidade,
		String maiorDificuldade,
		String necessitaAdaptacoes,
		String reacaoMudancas,
		String hiperfoco,
		List<String> formasAprendizagem,
		String responsavelRespondente,
		String rotinaCasa,
		String expectativasFamilia,
		String orientacaoImportante,
		String comportamentosForaEscola,
		String observacaoSalaOutrosEspacos,
		String professorRegente,
		String salaRecursos,
		String equipePedagogica,
		String observacoesGerais) {}
