import { StyleSheet } from 'react-native';

import { colors } from './colors';

export const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  safe: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  modernHeader: {
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    elevation: 5,
    overflow: 'hidden',
    shadowColor: colors.purple,
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
  },
  modernHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 64,
    paddingHorizontal: 8,
  },
  modernHeaderAction: {
    height: 48,
    margin: 0,
    width: 48,
  },
  modernHeaderTitle: {
    color: colors.ink,
    flex: 1,
    fontFamily: 'Nunito_800ExtraBold',
    letterSpacing: 0,
    textAlign: 'center',
  },
  screen: {
    gap: 14,
    padding: 16,
    paddingBottom: 118,
  },
  centered: {
    alignItems: 'center',
    backgroundColor: colors.bg,
    flex: 1,
    gap: 16,
    justifyContent: 'center',
  },
  loadingLogo: {
    height: 150,
    width: 150,
  },
  loginWrapper: {
    backgroundColor: colors.bg,
    flex: 1,
  },
  loginScroll: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 22,
    paddingBottom: 80,
    backgroundColor: colors.white,
  },
  loginLogo: {
    alignSelf: 'center',
    height: 250,
    marginBottom: 8,
    width: '100%',
  },
  authHero: {
    alignItems: 'center',
    marginBottom: 10,
  },
  authCurve: {
    borderBottomColor: colors.purple,
    borderBottomWidth: 2,
    borderRadius: 200,
    height: 22,
    opacity: 0.45,
    width: '96%',
  },
  authCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    elevation: 0,
  },
  authTitle: {
    color: colors.ink,
    fontWeight: '900',
    textAlign: 'center',
  },
  authSubtitle: {
    color: colors.muted,
    marginBottom: 8,
    textAlign: 'center',
  },
  authFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  primaryButtonContent: {
    minHeight: 58,
  },
  alignEnd: {
    alignSelf: 'flex-end',
  },
  registerScroll: {
    flexGrow: 1,
    padding: 22,
    paddingBottom: 120,
    backgroundColor: colors.white,
  },
  registerHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 10,
  },
  registerLogo: {
    alignSelf: 'center',
    height: 118,
    marginVertical: 16,
    width: 118,
  },
  firstAccessLogo: {
    alignSelf: 'center',
    height: 180,
    width: 180,
  },
  loginCard: {
    borderRadius: 22,
  },
  card: {
    borderRadius: 20,
    elevation: 1,
    shadowColor: colors.purple,
    shadowOpacity: 0.06,
    shadowRadius: 10,
  },
  inactiveCard: {
    backgroundColor: colors.inactiveBg,
    borderColor: colors.inactiveBorder,
    borderWidth: 1,
  },
  inactiveText: {
    color: colors.inactive,
  },
  inactiveChip: {
    backgroundColor: '#EAECF0',
  },
  inactiveChipText: {
    color: colors.inactive,
  },
  headerCard: {
    borderRadius: 20,
    overflow: 'hidden',
  },
  headerContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  headerText: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 12,
  },
  smallLogo: {
    height: 58,
    width: 58,
  },
  title: {
    color: colors.ink,
    fontWeight: '800',
  },
  muted: {
    color: colors.muted,
  },
  formGap: {
    gap: 16,
  },
  formField: {
    gap: 8,
    width: '100%',
  },
  formFieldLabel: {
    color: colors.tealDark,
    fontFamily: 'Nunito_800ExtraBold',
    fontSize: 12,
    letterSpacing: 0.6,
    marginLeft: 4,
    textTransform: 'uppercase',
  },
  formInput: {
    backgroundColor: colors.inputBg,
    fontFamily: 'Nunito_400Regular',
    minHeight: 64,
  },
  formInputDisabled: {
    backgroundColor: '#F3F7F6',
  },
  formInputContent: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 16,
    minHeight: 64,
    paddingHorizontal: 18,
  },
  formInputMultiline: {
    minHeight: 110,
    paddingTop: 16,
    textAlignVertical: 'top',
  },
  formInputOutline: {
    borderRadius: 22,
    borderWidth: 1.5,
  },
  listInputGroup: {
    gap: 8,
  },
  photoPicker: {
    alignItems: 'center',
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    padding: 12,
  },
  studentPhoto: {
    borderRadius: 46,
    height: 92,
    width: 92,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  statCard: {
    borderRadius: 18,
    flexBasis: '31%',
    flexGrow: 1,
    minWidth: 104,
  },
  statContent: {
    alignItems: 'center',
    gap: 6,
  },
  statValue: {
    color: colors.ink,
    fontWeight: '900',
  },
  quickGrid: {
    gap: 10,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  actionTile: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    elevation: 1,
    flexBasis: '30%',
    flexGrow: 1,
    gap: 6,
    minHeight: 106,
    padding: 10,
    shadowColor: '#0F172A',
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  actionIconCircle: {
    backgroundColor: '#F2ECFF',
    margin: 0,
  },
  actionTileText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  sectionTitle: {
    color: colors.ink,
    fontWeight: '800',
  },
  search: {
    backgroundColor: colors.white,
    borderColor: colors.inputBorder,
    borderRadius: 22,
    borderWidth: 1,
    elevation: 0,
  },
  itemRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
  },
  itemTitle: {
    color: colors.ink,
    fontWeight: '800',
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  statusChip: {
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  divider: {
    marginVertical: 12,
  },
  rowEnd: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  fab: {
    backgroundColor: colors.yellow,
    bottom: 104,
    position: 'absolute',
    right: 22,
  },
  empty: {
    alignItems: 'center',
    gap: 12,
    paddingVertical: 22,
  },
  profileHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  profilePhoto: {
    borderRadius: 38,
    height: 76,
    width: 76,
  },
  profilePhotoPicker: {
    alignItems: 'center',
    backgroundColor: colors.tealSoft,
    borderColor: '#C8EEE5',
    borderRadius: 20,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  profilePhotoLarge: {
    borderColor: colors.white,
    borderRadius: 56,
    borderWidth: 4,
    height: 112,
    width: 112,
  },
  profilePhotoActions: {
    alignItems: 'center',
    gap: 4,
    width: '100%',
  },
  fileActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
    marginTop: 8,
  },
  infoLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  infoValue: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 21,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  infoTile: {
    backgroundColor: colors.white,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    gap: 4,
    padding: 10,
  },
  infoTileFull: {
    flexBasis: '100%',
  },
  horizontalTabs: {
    gap: 8,
    paddingVertical: 4,
  },
  tabChip: {
    borderRadius: 16,
  },
  filterGrid: {
    gap: 10,
  },
  stepHeader: {
    backgroundColor: '#F0FBF8',
    borderColor: '#DDF8F0',
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  stepProgress: {
    borderRadius: 8,
    height: 8,
  },
  responsavelBox: {
    backgroundColor: '#FBF8FF',
    borderColor: colors.lavender,
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 10,
  },
  clinicalItemBox: {
    backgroundColor: colors.tealSoft,
    borderColor: '#C8EEE5',
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  investigationOption: {
    alignItems: 'center',
    backgroundColor: colors.lavenderSoft,
    borderColor: colors.lavender,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 78,
    padding: 14,
  },
  stepActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'flex-end',
  },
  documentHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  documentDescription: {
    color: colors.ink,
    lineHeight: 20,
    marginTop: 4,
  },
  fileActions: {
    gap: 10,
  },
  errorText: {
    color: colors.danger,
  },
  viewer: {
    backgroundColor: colors.ink,
    flex: 1,
  },
  viewerImage: {
    flex: 1,
    height: '100%',
    width: '100%',
  },
  webViewer: {
    flex: 1,
  },
  sessionHeader: {
    borderRadius: 0,
  },
  sessionPage: {
    backgroundColor: colors.bg,
  },
  sessionPageScroll: {
    paddingBottom: 42,
  },
  sessionHero: {
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    marginBottom: 22,
    padding: 16,
    paddingBottom: 24,
  },
  sessionSummaryCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    elevation: 4,
    shadowColor: colors.purple,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
  },
  sessionSummaryContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 88,
  },
  sessionMeta: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 24,
  },
  sessionMetaStrong: {
    color: colors.ink,
    fontFamily: 'Nunito_800ExtraBold',
  },
  sessionElapsedBox: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  sessionClockIcon: {
    backgroundColor: colors.lavenderSoft,
  },
  sessionElapsed: {
    color: colors.purple,
    fontFamily: 'Nunito_800ExtraBold',
  },
  sessionSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  sessionStudentsRow: {
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  sessionStudentCard: {
    backgroundColor: colors.white,
    borderBottomWidth: 4,
    borderRadius: 18,
    elevation: 2,
    minWidth: 190,
  },
  sessionStudentContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 72,
    paddingHorizontal: 10,
  },
  sessionRecordCount: {
    color: colors.tealDark,
    fontSize: 12,
    fontWeight: '800',
  },
  sessionShortcutGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    padding: 16,
    paddingTop: 12,
  },
  sessionShortcutCard: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    elevation: 1,
    flexBasis: '21%',
    flexGrow: 1,
    gap: 7,
    justifyContent: 'center',
    minHeight: 105,
    minWidth: 72,
    padding: 8,
  },
  sessionShortcutIcon: {
    alignItems: 'center',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  sessionShortcutText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 15,
    textAlign: 'center',
  },
  newObservationButton: {
    alignItems: 'center',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginHorizontal: 16,
    minHeight: 60,
    paddingHorizontal: 18,
  },
  newObservationText: {
    color: colors.white,
    fontFamily: 'Nunito_800ExtraBold',
  },
  sessionStopButton: {
    borderRadius: 18,
    marginHorizontal: 16,
    marginTop: 12,
  },
  sessionStopButtonContent: {
    minHeight: 64,
  },
  sessionContent: {
    flex: 1,
    padding: 16,
  },
  sessionScroll: {
    gap: 12,
    paddingBottom: 40,
  },
  timelineHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  timelineTime: {
    color: colors.tealDark,
    fontWeight: '900',
  },
  sheetBackdrop: {
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  bottomSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '88%',
  },
  bottomSheetContent: {
    gap: 12,
    padding: 16,
    paddingBottom: 32,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  activeSessionCard: {
    borderColor: colors.teal,
    borderWidth: 1,
  },
  activeChip: {
    backgroundColor: '#DDF8F0',
  },
  appTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 62,
    paddingHorizontal: 8,
  },
  appTopBarGradient: {
    borderRadius: 22,
    elevation: 3,
    marginBottom: 4,
    overflow: 'hidden',
    shadowColor: colors.purple,
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  compactPageHeader: {
    alignItems: 'center',
    borderRadius: 20,
    gap: 3,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  compactPageTitle: {
    color: colors.ink,
    fontFamily: 'Nunito_800ExtraBold',
    letterSpacing: 0,
    textAlign: 'center',
  },
  compactPageSubtitle: {
    color: colors.muted,
    textAlign: 'center',
  },
  logoRow: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 2,
  },
  topLogoIcon: {
    height: 42,
    width: 42,
  },
  topLogoWord: {
    height: 46,
    width: 118,
  },
  topBrandName: {
    color: colors.purple,
    fontWeight: '900',
  },
  topActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 2,
  },
  topAvatar: {
    backgroundColor: colors.lavender,
    borderColor: colors.yellow,
    borderWidth: 2,
  },
  brandHero: {
    backgroundColor: colors.lavender,
    borderRadius: 22,
    overflow: 'hidden',
  },
  welcomeCard: {
    backgroundColor: '#F0FBF8',
    borderColor: '#DDF8F0',
    borderRadius: 20,
    borderWidth: 1,
  },
  gradientCard: {
    backgroundColor: colors.purple,
    borderBottomColor: colors.teal,
    borderBottomWidth: 5,
    borderRadius: 20,
    borderRightColor: colors.yellow,
    borderRightWidth: 5,
  },
  gradientCardTitle: {
    color: colors.white,
    fontWeight: '900',
  },
  gradientCardSubtitle: {
    color: colors.white,
    opacity: 0.92,
  },
  brandHeroContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    minHeight: 128,
  },
  brandHeroTitle: {
    color: colors.ink,
    fontWeight: '900',
    lineHeight: 32,
  },
  brandHeroSubtitle: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
  heroLogoMark: {
    height: 118,
    opacity: 0.95,
    width: 118,
  },
  bottomMenu: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderTopColor: colors.line,
    borderTopWidth: 1,
    bottom: 0,
    elevation: 12,
    flexDirection: 'row',
    justifyContent: 'space-around',
    left: 0,
    paddingBottom: 10,
    paddingTop: 8,
    position: 'absolute',
    right: 0,
  },
  bottomMenuItem: {
    alignItems: 'center',
    flex: 1,
    minHeight: 64,
  },
  bottomIconWrap: {
    alignItems: 'center',
    borderRadius: 16,
    height: 40,
    justifyContent: 'center',
    width: 46,
  },
  bottomIcon: {
    margin: 0,
  },
  bottomPrimaryButton: {
    backgroundColor: colors.purple,
    borderRadius: 28,
    height: 58,
    marginTop: -26,
    width: 58,
  },
  bottomActive: {
    backgroundColor: '#F2ECFF',
  },
  bottomLabel: {
    color: colors.muted,
    fontSize: 11,
    marginTop: 2,
  },
  bottomLabelActive: {
    color: colors.purple,
    fontWeight: '800',
  },
  sideOverlay: {
    flex: 1,
    flexDirection: 'row',
  },
  sideDim: {
    backgroundColor: 'rgba(0,0,0,0.38)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  sidePanel: {
    backgroundColor: colors.white,
    borderBottomRightRadius: 8,
    borderTopRightRadius: 8,
    elevation: 16,
    overflow: 'hidden',
    width: '82%',
  },
  sideHeader: {
    minHeight: 190,
    padding: 22,
    paddingTop: 34,
  },
  sideClose: {
    alignSelf: 'flex-end',
    margin: 0,
  },
  sideAvatar: {
    backgroundColor: colors.white,
    marginBottom: 12,
  },
  sideName: {
    color: colors.white,
    fontWeight: '900',
  },
  sideRole: {
    color: colors.white,
    opacity: 0.9,
  },
  sideItems: {
    padding: 14,
  },
  sideItem: {
    alignItems: 'center',
    borderRadius: 16,
    flexDirection: 'row',
    minHeight: 54,
  },
  sideItemText: {
    color: colors.ink,
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
  },
  aboutCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
  },
  aboutLogo: {
    alignSelf: 'center',
    height: 180,
    width: '100%',
  },
  anamneseAccordionContent: {
    gap: 10,
    paddingBottom: 14,
    paddingHorizontal: 14,
  },
  anamneseSearchResult: {
    backgroundColor: colors.white,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
});
