server:
  port: ${PORT:8080}

spring:
  application:
    name: eloviaapi

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require}
    username: ${DATABASE_USERNAME:postgres.citxmlurmzvkokjbtnhh}
    password: ${DATABASE_PASSWORD:TROQUE_PELA_SUA_SENHA}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
